### ISSUE TITLE
Inconsistency on onMessageReceived Bundle reader

### ISSUE THREAD

**Issue by tariana** [RoverPlatform/rover-android#12]
Where: RoverGcmListenerService class, onMessageReceived method.

Inside the received Bundle there is a key called “message” and the value is a Json containing the attributes: “type”, “id” and “attributes”. See example bellow.

The onMessageReceived method is trying to get all the keys (“attributes”, “type” and “id”) directly from the Bundle, can’t find them and logs a "Bad data bundle for Gcm” error. The message then is never shown.

Example:
{
    "attributes": {
        "notification-text": "android test",
        "android-title": "LoyaltyOne",
        "read": false,
        "website-url": null,
        "ios-title": "LoyaltyOne",
        "saved-to-inbox": false,
        "deep-link-url": null,
        "content-type": "custom",
        "properties": {
            "message": "hello!"
        },
        "tags": [],
        "timestamp": "2016-06-24T19:00:05.583Z"
    },
    "id": "576d83352c5e2a00270926f3",
    "type": "messages"
}

**Comment by ata-n** [comment]
This was addressed in issue #8 #6
