### ISSUE TITLE
Most of the Events are more like Messages.  Mostly.  Consider renaming.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#193]
See https://www.reactivemanifesto.org/glossary#Message-Driven

**Comment by seanrucker** [comment]
- App Opened
- App Updated
- Experience Viewed
- Block Clicked
- Geofence Entered

... these are events, no?

**Comment by orospakr** [comment]
@seanrucker ah this is a terminology collision.  Not referring to Rover events as such, referring to Events being emitted from ViewModels to update the UI (experience loaded, navigation back and forth, that sort of thing).

**Comment by seanrucker** [comment]
Ahh gotcha

**Comment by orospakr** [comment]
this is wrong anyway because "Message" means it's addressed to something, but these are not.
