### ISSUE TITLE
Bug when I tried to open a Landing page type from Notification bar

### ISSUE THREAD

**Issue by andresrubianoch10** [RoverPlatform/rover-android#197]
After a deep process, I can see URL is malformed (image attached). The snippet code to create an intent is the same like this repo sample. The notification is created normally from rover platform.

<img width="859" alt="malformedurl" src="https://user-images.githubusercontent.com/7076009/36100007-afbdfe7c-0fd2-11e8-9aec-6f4e6d425cb7.png">

<img width="516" alt="rover 2" src="https://user-images.githubusercontent.com/7076009/36099978-934a5e8e-0fd2-11e8-93c9-f80ec2d5286d.png">

**Comment by seanrucker** [comment]
How prevalent is this issue? Is it a showstopper for you or an edge case?

**Comment by andresrubianoch10** [comment]
Hi  @seanrucker 
This happen every time when I try to open a landing page type notification. This is a big blocker because I can't take new release candidate without finish this new feature.

**Comment by seanrucker** [comment]
@orospakr can you take a look at this?

**Comment by andresrubianoch10** [comment]
Maybe this could be helpful, but Other notification type like deep link, website and experience has been working perfect. This issue only happen when I create a new notification with landing page type from rover platform. 

CC @seanrucker  @orospakr

**Comment by seanrucker** [comment]
@MitulanyQuilla do you know if your end user (whoever will be using the Messages app) will be using landing pages? We've been suggesting to customers to stick with Experiences and avoid landing pages as they will eventually be deprecated.

**Comment by andresrubianoch10** [comment]
@seanrucker We're using FCM+rover. How can I to figure out if FCM is working with Landing pages?

**Comment by orospakr** [comment]
Hi @MitulanyQuilla, would you mind getting back to the same breakpoint from where you pasted the screenshot, and inspecting the `MalformedURLException` to see more details about what went wrong?

**Comment by andresrubianoch10** [comment]
Hi @orospakr  I've been trying to check MalformedURLException but it has been impossible. I'm trying to evaluate the instance but Android Studio shown there's nothing to evaluate. Also I tried to wrote some snippet code but that class is into library. For that reason, I'm not allow to write. 

If you know a way that I can do to see MalformedURLException, please, don't hesitate in tell me what it is.

**Comment by orospakr** [comment]
Hi @andresrubianoch10, just a quick sanity check: please check that your app has the INTERNET permission added.

**Comment by andresrubianoch10** [comment]
@orospakr yeah, The application has android internet permission and NETWORK_STATE too in Android Manifest.

**Comment by orospakr** [comment]
Closing this because SDK 1.x is deprecated.  If you're still trying to make this work, please give SDK 2.x a try: https://developer.rover.io/android/
