### ISSUE TITLE
Track sender id

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-android#201]
To be able to properly select which credentials to use for push notifications Rover needs to know the sender id of the device.

**Comment by chrisrecalis** [comment]
@orospakr what do you currently track in `appNamespace` inside the context?

**Comment by orospakr** [comment]
@chrisrecalis this is sorted now, right?

**Comment by chrisrecalis** [comment]
yes we associate app_identifier to creds now
