### ISSUE TITLE
Create Sample App for Rover SDK

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#341]
It should live in the SDK repo as `sample-app`.

For clarity, Rover SDK means the Experiences-only SDK, not the Campaigns SDK.

It should have a simple README introducing itself.

It should demonstrate importing the SDK, initializing it, setting the auth token, embedding the RoverActivity in your manifest, and then launching an experience.

It should also introduce how to set up deep and universal links handlers for opening experiences.

**Comment by samwoodall** [comment]
PR: https://github.com/RoverPlatform/rover-android/pull/349
