### ISSUE TITLE
Strongly typed Events (rather than wrapped stringly typed Events)

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#355]
- [x] Event sealed class with class for each of the event types (ExperiencePresented, ScreenViewed, etc.);
- [x] Remove LocalBroadcastManager support;
- [x] Add `addListener` method to EventEmitter that accepts an interface with a method for each event type.  eg. `fun ExperiencePresented(val experience: Experience)`.

**Comment by samwoodall** [comment]
PR: https://github.com/RoverPlatform/rover-android/pull/357
