### ISSUE TITLE
Allow end to end serialization test to run with stock experience.json without massaging.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#362]
Right now deprecated fields (campaignID and isImageOptimizationEnabled) are included in `...experienceFields`, meaning JSONs we return will be missing those fields after round tripping serialization, failing the JSONAssert tests.

**Comment by samwoodall** [comment]
(from Andrew) a better solution is that the fragments `...experienceFields` on graphql-gateway should be versioned, ie., `...experienceFields` (no 2 for backwards compatibility) and `...experienceFields3`.  That way we can be sure that we aren't receiving unnecessary fields.

**Comment by samwoodall** [comment]
(from Andrew) deferring this for now until we can do the above (or otherwise better) solution other than hacking up the tests even more or adding in dummy fields in our model objects.
