### ISSUE TITLE
Test that Ticketmaster (and advertising) modules work.

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#388]
Integrate and test TM and confirm that the behaviour in the new SDK is correct.

- [ ] Take campaigns example app, and install the TM presence SDK: https://developer.ticketmaster.com/products-and-docs/sdks/presence-sdk/android/index.html ;
- [ ] Install the Rover Ticketmaster module, and integrate it with the Ticketmaster presence SDK .
- [ ] Reach out to @orospakr for credentials for a TM team;
- [ ] use the Ticketmaster steps in the integration test plan to verify that it is working: https://github.com/RoverPlatform/rover-campaigns-android/wiki/Test-Plan ;
- [ ] while doing the test plan, pay extra close attention to the to the `ticketmasterhostMemberID` and `ticketmasterteamMemberID` fields (ignore any capitalization problems).  The team member ID is the important one because we actually only support Archtics integration on the server side.
- [x] ensure advertising behaves as expected

**Comment by samwoodall** [comment]
sent as `hostMemberID` and `teamMemberID`
If one is set, it overwrites the other, so only one can be set at a time.
So, we on the server side could just take whatever the value is and treat that as the ID
