### ISSUE TITLE
Specify exact parameters for Polls animations

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#391]
* Tap & reveal results for image polls
* Tap & reveal results for text polls (including progress-bar-like result meter)

Work with Andrea to nail down the three important parameters for each animations:
* order/sequence (ie., should number fade in after or during progress bar animation)
* function (ease in/out, bounce, linear, quadratic, etc.)
* duration

**Comment by samwoodall** [comment]
### Text Poll Animation
- Whole animation is 1000millis
- All animations start at 0millis
- All animation uses ease in ease out interpolation
- Opacity of vote percentage and voting indicator from 0 -> 1 takes 750millis
- Opacity of results fill bar from 0 -> 1 takes 50millis
- Result color bar fill and result percentage incrementation duration is 1000millis

For the ease in ease out function I’m going to use this equation `y = x^2/(2*(x^2-x)+1)`
The curve of this looks like 
![Screen Shot 2019-06-28 at 10.59.24 AM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/249f7e1b-e5c4-4bdf-9330-61570a1bca86/Screen+Shot+2019-06-28+at+10.59.24+AM.png)

 Here's the animation 
https://www.dropbox.com/sh/u7yjzret0jkqv6l/AAA5AHcPPKFGvNXF6DAtbTbSa?dl=0
