### ISSUE TITLE
Plan Support for Q SDK

### ISSUE THREAD

**Issue by orospakr** [RoverPlatform/rover-android#406]
* Target Q - 1 (so, Oreo.  We can't target Q directly because as a rule we always adopt $current-sdk - 1 in order to support developers who are trailing behind by one release without causing issues with transitive dependencies);
* Bump example app to target Q to test that using our SDK in a Q-targetted app works correctly without regression;
* Identify any new platform features introduced in Oreo (Q - 1) that we can now take advantage of, and make tickets for them;
* Check for any other ramifications of consuming apps targeting Q.

Ensure following cases work:
1. App not targeting Q is running on Q.
2. App targeting Q is running on Q. Necessary compatibility modes that make 1. case work may fail on 2.

This ticket needs to be released in an SDK minor version within one week of the Q retail release (probably August-ish).

**Comment by samwoodall** [comment]
We don't need to make any changes to the Rover sdk for compatibility with apps targeting or running on Q

**Comment by orospakr** [comment]
@samwoodall what about representing the foreground-only location mode? Doesn't our permissions handling logic need to change to accommodate that?

**Comment by samwoodall** [comment]
For the Campaigns sdk we will, but not for the Rover sdk

**Comment by orospakr** [comment]
LOL 💩
