### ISSUE TITLE
Paragraph Spacing

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-android#451]
One of our customers have identified a recurring issue involving paragraph breaks on Rover pages. If they add a paragraph break with a blank link in between, iOS devices apply the blank line in the experience, while Android doesn't include the blank line space.

They claim they have found two workarounds to this issue:
1. Create a separate text section and add margin, or 
2. Add a space character to the blank line so that Android reads in at a new line and not empty

We were unable to verify they are in fact valid workarounds to the issue. You can view this by looking at the paragraphs on the home screen of the experience with ID: `5da5f23987732a00157802ae`.

**Comment by samwoodall** [comment]
Based upon testing these work arounds are valid and provide the correct behaviour. There's some functionality in the `TextBlock` that deletes blank lines that should be removed.

**Comment by seanrucker** [comment]
Thanks for testing and looking into this. Good to know the workarounds are valid. We will figure out when to prioritize the work to fix this.
