### ISSUE TITLE
Incorrect option id when voting on a poll

### ISSUE THREAD

**Issue by chrisrecalis** [RoverPlatform/rover-android#452]
When tracking a `Poll Answered` event the incorrect option id is being passed in. It is instead settings the `attributes.option.id` to the poll id

**Comment by orospakr** [comment]
@chrisrecalis hey, what was the customer complaint/symptom associated with this issue? just trying to gain some context

**Comment by chrisrecalis** [comment]
Its just a bug I uncovered while writing queries for retargeting campaigns based on the `Poll Answered` event
